LibroLibre/LibroLibre/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url('', include('social.apps.django_app.urls', namespace='social')),

	url(r'^usuarios/', include('usuarios.urls',namespace="usuarios")),
	url(r'^libros/', include('libros.urls',namespace="libros")),


]

LibroLibre/libros/urls.py
from django.conf.urls import url
from . import views

app_name = 'libros'
urlpatterns = [
	url(r'^todos/$',
		views.LibroView.as_view(),
		name="todos"),

	url(r'^detalle/(?P<slug>\d+)/$',
		views.LibroDetailView.as_view(),
		name="detalle"),

	url(r'^api/$',
		views.Api.as_view(),
		name="api"),
]

LibroLibre/usuarios/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as loginViews

app_name = 'usuarios'
urlpatterns=[
	url(r'^login/$',
		loginViews.login,
		name="login"),
	url(r'^logout/$',
		loginViews.logout,
		name="logout"),
]

LibroLibre/libros/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.

class Libro(models.Model):
	titulo=models.CharField(max_length=50,blank=True,null=True)
	slug=models.SlugField(max_length=50,blank=True,null=True)
	autor=models.CharField(max_length=30,blank=True,null=True)
	libro_isbn = models.CharField(max_length=13)
	fecha=models.DateTimeField(auto_now=True)
	publicado=models.BooleanField(default=True)
	usuario=models.ForeignKey(User,related_name='libros_publicados',blank=True,null=True)

	def __str__(self):
		return self.titulo

	def get_absolute_url(self):
		return reverse('libros:detalle', args=[self.slug])

	def publicado_recientemente(self):
		return self.fecha >= timezone.now() - datetime.timedelta(days=1)

LibroLibre/usuarios/models.py
from django.db import models

# Create your models here.

LibroLibre/libros/forms.py
from django import forms 
from .models import Libro

class LibroForm(forms.ModelForm):
	class Meta:
		model=Libro
		fields=('libro_isbn',)
		

LibroLibre/usuarios/forms.py
from django import forms 

class LoginForm(forms.Form):
	username=forms.CharField()
	password=forms.CharField(
		widget=forms.PasswordInput)

LibroLibre/libros/views.py
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from .models import Libro
from django.views.generic import View
from .forms import LibroForm
from django.http import HttpResponseRedirect
from django.template import loader
from django.core import serializers
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.

class LibroView(View):
	def get(self,request):
		template="libros/todos.html"
		libros=Libro.objects.all()
		form=LibroForm()
		context={
		'libros':libros,
		'form':form
		}
		return render(request,template,context)
	def post(self,request):
		form=LibroForm(request.POST)
		form.save()
		return redirect('libros:todos')

class LibroDetailView(View):
	@method_decorator(login_required(login_url='usuarios:login'))
	def get(request, slug):
		libros=Libro.objects.get(slug)
		form=LibroForm()
		template="libros/detalle.html"
		context={
		'libros':libros,
		'form':form
		}
		return render(request,template,context)

class Api(View):
	def get(self,request):
		libros=Libro.objects.all()
		data=serializers.serialize('json',libros)
		return HttpResponse(data,content_type='application/json')

LibroLibre/usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import LoginForm
from django.contrib.auth import authenticate, login

# Create your views here.

class LoginView(View):
	def get(self,request):
		form=LoginForm()
		template_name="usuarios/login.html"
		context={
		'form':form
		}
		return render(requerst,template_name,context)

	def post(self,request):
		form=LoginForm(request.POST)
		if form.is_valid():
			cd=form.cleaned_data
			user=authenticate(username=cd['username'],
				password=cd['password'])
			if user is not None:
				login(request,user)
				return redirect('libros:todos')
			else:
				return render(request,"usuarios/login.html",{'form':form})

LibroLibre/libros/templates/base.html
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{%static 'estilo.css'%}">
</head>
<body>

	{%block content%}
	{%endblock content%}

</body>
</html>

LibroLibre/libros/templates/libros/detalle.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

<section class="container">

<h1>{{libro.titulo}}</h1>
<h2>{{libro.autor}}</h2>
<h4>ISBN: {{libro.libro_isbn}}</h4>
<p>{{libro.fecha}}</p>

</section>

LibroLibre/libros/templates/libros/todos.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%load static%}

{%block content%}

	<h1>Todos los Libros</h1>

	{% for libro in libros %}
	<a href="{{libro.get_absolute_url}}">
		<h2>{{libro.titulo}}</h2>
	</a>
	{%endfor%}

	<h2>Nuevo Libro:</h2>
	<form action="." method="post">
		{{form.as_p}}
		{% csrf_token %}
		<p><input type="submit" value="Publicar"></p>
	</form>

{%endblock content%}

LibroLibre/templates/base.html
{%load static%}
<html>
<head>
	<title>Libro Libre</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

  <link rel="stylesheet" type="text/css" href="{%static 'estilo.css'%}">



</head>
<body>
	  <nav>
    <div class="nav-wrapper">
      <a href="{% url 'libros:todos' %}" class="brand-logo">Libro Libre</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li>
          {%if request.user.is_authenticated%}
            Hola {{request.user.username}}!
        </li>
        <li>
                      <a href="{%url 'usuarios:logout'%}">
              Cerrar Sesión
            </a>

          {%else%}
             <a href="{%url 'usuarios:login'%}">
             Inicia Sesión</a>
          {%endif%}
        </li> 
      </ul>

    </div>
  </nav>

  {% block content %}

  {% endblock content %}

<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
 <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

  <script type="text/javascript">
  $( document ).ready(function(){

  	$(".button-collapse").sideNav();

  });
  </script>
    
</body>
</html>

LibroLibre/usuarios/templates/usuarios/login.html
{% extends 'base.html' %}
{%load static%}

{% block content %}

<section class="section">
  <article class="container">

    <div class="row">

    <form action="." method="post">
      {%csrf_token%}
      {{form.as_p}}
  		<input type="submit" value="Entrar">
	  </form>

    </div>
  </article>
</section>
	


{% endblock content %}